apiVersion: v1
kind: Secret
metadata:
  name: paperless-webdav
  namespace: default
type: Opaque
stringData:
  ENCRYPTION_KEY: "Zc4B8SINe5n8pHgDx477+lgTlchxkQqhnlKoMv3fWO0="
  SECRET_KEY: "k8s-secret-key-for-paperless-webdav-sessions"
